### ISSUE TITLE
not al allowed extentions can be upload

### ISSUE THREAD

**Issue by johanpeters** [dgrammatiko/jailed-fs#167]
not all allowed extentions (file type) can be uploaded when FS plugin is enabled.
with FS plugin disabled file type can be uploaded.. (
png works, pfd, pptx works not as example.
perhaps partly a relation with other issue reported regarding Media Provider not found.?

**Comment by dgrammatiko** [comment]
Please make sure that there is a selected (the name should be bold) adapter (ie click on the square below the RestrictedFS)
<img width="337" alt="Screenshot 2023-03-03 at 15 39 37" src="https://user-images.githubusercontent.com/3889375/222749154-c3076801-eb4e-4151-8b05-589ba0ec5ecf.png">
