### ISSUE TITLE
Not jailed anymore

### ISSUE THREAD

**Issue by wunschradio** [dgrammatiko/jailed-fs#234]
Hi,

since one of the last Joomla updates the plugin does not work anymore as expected on my site. The user has access to own files and the main images folder.

![Screenshot](https://github.com/dgrammatiko/jailed-fs/assets/39115843/af29f3cc-9d46-4306-947f-8ec737c63c8d)

It worked perfect before. Could you please check?

**Comment by dgrammatiko** [comment]
I cannot replicate it locally. Could you please provide more info:
- user group(s) assigned
- other extensions used

Thanks

**Comment by wunschradio** [comment]
I have already checked all extensions. What I mean is the seconds folder structure on top of the userfolder called "local".
![local](https://github.com/dgrammatiko/jailed-fs/assets/39115843/42687846-fcbc-4df3-824f-a4c5221f77b0)
With this the user can access all files in images folder. 

I could verify that this comes from the Joomla original system plugin "FileSystem - Local". If I add more folders there they will also be available
![media](https://github.com/dgrammatiko/jailed-fs/assets/39115843/69c45a16-3d6d-4c4a-8a9b-dbb7b2f4d60f)

So I could set up a workaround by using an empty folder within this core plugin. If I unpublish this core plugin I get the error "No filesystem providers have been found. Please enable at least one filesystem plugin".

**Comment by dgrammatiko** [comment]
@wunschradio I still cannot replicate it locally. Could you provide:
- the user group assigned to the restricted FS plugin
- the user group for the Local FS
- the permissions for all the user groups for the media component

Or you could create a temporary admin user and send me the password at d dot grammatiko at gmail dot com
