### ISSUE TITLE
v 1.3.1 doesn't install

### ISSUE THREAD

**Issue by DeMiro5001** [dgrammatiko/jailed-fs#563]
I have tried to install it from the web but joomla 5 said it didn't find the manifest.
I downloaded the file, opened it with the windows explorer, it was empty. Winrar and 7zip found the files, so I recompressed the content of the archive and launched the install and it succeeded.
Thanks a lot for your work

**Comment by dgrammatiko** [comment]
I can't replicate it. What's your operating system?

**Comment by DeMiro5001** [comment]
On windows 11, the file explorer says the zip is empty. But with mx linux the file is correctly opened.
On 7zip, when I open it, it shows this
![Capture d'écran 2024-08-20 192002](https://github.com/user-attachments/assets/84f52ec1-b228-42ae-8293-3630b3193e42)
When I open that folder it shows the content of the zip, note the double "\\"
![Capture d'écran 2024-08-20 192013](https://github.com/user-attachments/assets/00981678-4aee-4081-92ac-7ea5c9a0589b)

**Comment by dgrammatiko** [comment]
This has been fixed upstream, next version won’t have windows issues
