### ISSUE TITLE
Error in Frontend

### ISSUE THREAD

**Issue by coolcat-creations** [dgrammatiko/jailed-fs#626]
Hi @dgrammatiko not sure if its from your plugin but I get COM_MEDIA_ERROR_MEDIA_PROVIDER_NOT_FOUND
Function
Location

0
JROOT/administrator/components/com_media/src/Provider/
ProviderManager.php:100
2
Joomla\Component\Media\Administrator\Provider\ProviderManager >getProviderQ
JROOT/administrator/components/com_media/src/Provider/
ProviderManager.php: 125
3
Joomla\ Component\Media\Administrator\Provider\ProviderManager->getAdapter0
JROOT/administrator/components/com_media/src/Provider/
ProviderManagerHelperTrait.php:97

class@anonymous/www/htdocs/plugins/editors/tinymce/src/PluginTraits/
Display Trait.php:333$9f-›getAdapter
JROOT/administrator/components/com_media/src/Provider/
ProviderManagerHelperTrait.php:151

class@anonymous/www/htdocs/plugins/editors/tinymce/src/PluginTraits/
Display Trait.php:333S9f->getDefaultAdapterName
JROOT/administrator/components/commedia/src/Provider/
ProviderManagerHelperTrait.php: 123

class@anonymous/www/htdocs/plugins/editors/tinymce/src/PluginTraits/
DisplayTrait.php:333$9f-›resolveAdapterAndPathQ
JROOT/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php:338

**Comment by dgrammatiko** [comment]
This is on the latest version of Joomla 5.2?

**Comment by coolcat-creations** [comment]
Yes, its 1.3.2 on Joomla 5.2

**Comment by coolcat-creations** [comment]
Let me check if its this: https://github.com/joomla/joomla-cms/pull/44313

**Comment by dgrammatiko** [comment]
@coolcat-creations does the PR on the Joomla repo solves the problem?

**Comment by coolcat-creations** [comment]
no unfortunately not, and I am also not sure if it's because of your plugin, a bit lost what is causing the issue.

**Comment by dgrammatiko** [comment]
@coolcat-creations i think we could close this one, if there’s another issue please open another issue (or reopen this one).

Thanks
